BASE_URL = 'https://stellarburgers.nomoreparties.site'
CREATE_USER_PATH = '/api/auth/register'
LOGIN_USER_PATH = '/api/auth/login'
AUTH_USER_PATH = '/api/auth/user'
ORDER = '/api/orders'
GET_INGREDIENTS = '/api/ingredients'
